name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Move files to docs folder
        run: |
          mkdir -p docs
          rsync -av --delete build/web/ docs/
    
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update GitHub Pages"
          branch: main
          file_pattern: docs/*